# Generated by Django 4.2.18 on 2025-09-06 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_work_minutes', models.IntegerField(default=525)),
                ('grace_period_minutes', models.IntegerField(default=90)),
                ('penalty_rate', models.DecimalField(decimal_places=1, default=1.4, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workshift')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_check_in', models.TimeField(null=True)),
                ('last_check_out', models.TimeField(null=True)),
                ('total_lateness_minutes', models.IntegerField(default=0)),
                ('penalty_minutes', models.FloatField(default=0)),
                ('required_work_minutes_today', models.FloatField(default=525)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
