# Generated by Django 4.2.18 on 2025-09-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendancereport',
            name='total_worked_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyattendancereport',
            name='work_overtime_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailyattendancereport',
            name='work_shortfall_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
