# Generated by Django 4.2.18 on 2025-09-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_workshift_user_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtimerequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='dailyattendancereport',
            name='first_check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyattendancereport',
            name='last_check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyattendancereport',
            unique_together={('employee', 'date')},
        ),
    ]
