# Generated by Django 4.2.18 on 2025-09-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='works_on_friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshift',
            name='works_on_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='works_on_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='works_on_sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='works_on_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='works_on_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workshift',
            name='works_on_wednesday',
            field=models.BooleanField(default=True),
        ),
    ]
