# Generated by Django 4.2.18 on 2025-09-07 21:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_workshift_works_on_friday_workshift_works_on_monday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='grace_period_minutes',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='penalty_rate',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='total_work_minutes',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='works_on_friday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='works_on_monday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='works_on_saturday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='works_on_sunday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='works_on_thursday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='works_on_tuesday',
        ),
        migrations.RemoveField(
            model_name='workshift',
            name='works_on_wednesday',
        ),
        migrations.AlterField(
            model_name='workshift',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='ShiftDayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_work_day', models.BooleanField(default=False)),
                ('start_time', models.TimeField(default=datetime.time(8, 0))),
                ('end_time', models.TimeField(default=datetime.time(16, 45))),
                ('required_work_minutes', models.IntegerField(default=525)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_rules', to='attendance.workshift')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('shift', 'day_of_week')},
            },
        ),
    ]
