# Generated by Django 4.2.18 on 2025-09-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_remove_workshift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftdayrule',
            name='grace_period_minutes',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='shiftdayrule',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=1, default=1.4, max_digits=3),
        ),
    ]
