# Generated by Django 4.2.18 on 2025-09-09 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_shiftdayrule_grace_period_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('mission_type', models.CharField(choices=[('FULL_DAY', 'Full-Day Mission'), ('HOURLY', 'Hourly Mission')], max_length=10)),
                ('start_time', models.TimeField(blank=True, help_text='Start time for hourly mission', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time for hourly mission', null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
