# Generated by Django 4.2.18 on 2025-09-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_manuallogrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_period_minutes', models.IntegerField(default=90)),
                ('penalty_rate', models.DecimalField(decimal_places=2, default=1.4, max_digits=3)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
        migrations.RemoveField(
            model_name='shiftdayrule',
            name='grace_period_minutes',
        ),
        migrations.RemoveField(
            model_name='shiftdayrule',
            name='penalty_rate',
        ),
    ]
