# Generated by Django 5.2.6 on 2025-09-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
