# Generated by Django 5.2.6 on 2025-09-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_overtimerequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='requested_minutes',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
